communitiesuk/funding-service-design-fund-store

app.py
manifest.yml
requirements-dev.txt
requirements.in
requirements.txt
tests/test_healthcheck.py

Added flask running healthcheck

added healthchecks

---

core/data_operations/fund_data.py

Need this to supply to the notification templates for the help contact details

added contact email to COF fund details

---

app.py
manifest.yml
requirements-dev.txt
requirements.in
requirements.txt

Adds sentry integration using utils function

FS-1401: sentry integration

---

.github/dependabot.yml
requirements-dev.in
requirements-dev.txt

Add configurable dependabot.yml file (https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleinterval).
I have enabled Dependabot security updates which will cause Dependabot to create pull requests for newly detected vulnerabilities outside of our regular update interval.

add dependabot.yml

---

core/data_operations/round_data.py

BAU: update application deadline

---

.github/workflows/tag-to-release.yaml

FS-2172: use shared workflow

---

.github/workflows/tag-to-release.yaml

Run action on merge to pick up workflow changes from https://github.com/communitiesuk/funding-service-design-workflows/pull/34

FS-2172: run action on merge

---

README.md
core/data_operations/fund_data.py
core/data_operations/round_data.py
core/db/db_connection.py
core/fund_round_dao.py
core/funds.py
core/rounds.py
manifest.yml
openapi/api.yml
tests/conftest.py
tests/test_funds.py

Adds /funds endpoint to retrieve all available funds. Used in FS-2181 to retrieve all available funds for displaying the dashboard in the frontend.

Fs 2181 all funds

---

requirements-dev.txt

Reverts communitiesuk/funding-service-design-fund-store#36

Revert "Bump pytest from 7.1.2 to 7.2.0"

---

core/data_operations/round_data.py

This ticket updates the assessment closing date to 17th May

FS-2671-wrong-closing-date-for-R2W3

---

core/data_operations/fund_data.py

This PR updates the fund name translation in Welsh

Updating translation for the fund name

---

Dockerfile
README.md
db/README
scripts/load_cof_r2.py
scripts/load_cof_r3w1.py
tasks.py

- Make it compatible to run on windows
- Added psql client in Dockerfile
- Updated tasks.py to run in container

added psql client in dockerfile & updated tasks file

---

scripts/load_cof_r3w1.py

https://digital.dclg.gov.uk/jira/browse/FS-2737
https://digital.dclg.gov.uk/jira/browse/FS-2739
Update script for local databases
`docker exec -it <container-id> psql postgresql://postgres:password@127.0.0.1:5432/fund_store -c "UPDATE \"public\".\"form_name\" SET \"form_name\" = 'risk-cof-r3-w1' WHERE \"section_id\" = 50 AND \"form_name\" = 'feasibility-cof-r3-w1'; UPDATE \"public\".\"form_name\" SET \"form_name\" = 'final-confirmations-cof-r3-w1' WHERE \"section_id\" = 59 AND \"form_name\" = 'project-information-cof-r3-w1'; UPDATE \"public\".\"section\" SET \"title\" = '6.1 Declarations' WHERE \"id\" = 59;"`
linking form fix 

Fix for load tree

---

config/fund_loader_config/cof/cof_r3.py

_Add ticket reference to Pull Request title: e.g. 'FS-123: Add content', if there is no ticket prefix with BAU_
https://digital.dclg.gov.uk/jira/browse/FS-2811
Updating form name to have declarations in the url

Updating round 3 config

---

config/fund_loader_config/cof/cof_r2.py
config/fund_loader_config/cof/cof_r3.py
config/fund_loader_config/night_shelter/ns_r2.py

https://digital.dclg.gov.uk/jira/browse/FS-2833
- Update fund store config dates
- Support "project-name" section
- give order integers to all section titles in NSTF and COFR3 (some of COFR2)
---
NA - fund config specific

FS-2833: Update dates, add before-you-start project name section config

---

config/fund_loader_config/night_shelter/ns_r2.py
scripts/data_updates/FS-2900-ns-section-update.py

https://digital.dclg.gov.uk/jira/browse/FS-2900
https://digital.dclg.gov.uk/jira/browse/FS-2912
https://digital.dclg.gov.uk/jira/browse/FS-2911
NSTF config typings corrected

update config and create update script

---

config/fund_loader_config/night_shelter/ns_r2.py
scripts/data_updates/FS-2965_ns_guidance.py

https://digital.dclg.gov.uk/jira/browse/FS-2965
Added Application guidance for NSTF
Added script to update guidance data, Run the below cmd 
locally, `python -m scripts.data_updates.FS-2965_ns_guidance`
On Test, `cf run-task funding-service-design-fund-store-test --command "python -m scripts.data_updates.FS-2965_ns_guidance"`
On Uat/Prod, `cf run-task funding-service-design-fund-store --command "python -m scripts.data_updates.FS-2965_ns_guidance"`

add application guidance for NSTF

---

api/routes.py
openapi/api.yml

https://dluhcdigital.atlassian.net/browse/FS-3103
- Added API to retrieve available teams in a round
- This is a short term solution for adding available teams in the fund-store. 
- Inspired from the @srh-sloan work [here](https://github.com/communitiesuk/funding-service-design-fund-store/blob/c6ced2ea521ce34118369b3be1ce1ad14796c6c4/api/routes.py#L141)

FS-3103 Added api to retrieve available teams

---

.github/workflows/deploy.yml
.github/workflows/package.yml
.github/workflows/tag-to-release.yaml
README.md

Updating the workflows so that on each branch update, a new image will be created, and on each merge to main an image will be created with matching tags
* Adding in Procfile for Paketo
* Adding package write permissions for deploy and tag/release
* Adding in build jobs
- [ N/A ] Unit tests and other appropriate tests added or updated
- [ X ] README and other documentation has been updated / added (if needed)
N/A

FS-2406: Adding Paketo build to workflow

---

Procfile

* Adding in Procfile which Paketo needs to run
+ref: FS-2406
+semver: minor
- [ X ] Unit tests and other appropriate tests added or updated
- [ X ] README and other documentation has been updated / added (if needed)

FS-2406: Adding Procfile

---

.github/workflows/deploy.yml

https://dluhcdigital.atlassian.net/browse/FS-3077
Split out unit testing for pre-deploy scripts when deploying to AWS.

FS-3077 - Split pre-deploy testing out for AWS

---

config/fund_loader_config/cof/cof_r3.py
db/migrations/versions/91934df64d2d_.py
db/models/round.py
db/models/section.py
db/queries.py
tests/test_schemas.py

- Add `requires_feedback` to schema for sections
- Add `requires_feedback` for end of application feedback survey
- Change COFR3W2 script to require feedback on some sections & the round
---

FS-3324: Change schema for requiring feedback

---

.github/workflows/deploy.yml
.github/workflows/tag-to-release.yaml

https://dluhcdigital.atlassian.net/browse/FS-3412
Correct some references to funding-design-service to be funding-service-design

FS-3412 fds -> fsd

---

copilot/environments/dev/manifest.yml

https://dluhcdigital.atlassian.net/browse/FS-3421
Add dev deployment to the copilot environments
- [n/a] Unit tests and other appropriate tests added or updated

FS-3421 Add dev deployment

---

api/routes.py

https://dluhcdigital.atlassian.net/browse/FS-3439
Added teams for cof r3w2

FS-3439 Added teams for cof r3w2

---

config/fund_loader_config/cyp/cyp_r1.py

cyp-config

---

config/fund_loader_config/cyp/cyp_r1.py

cyp-date-config

---

config/fund_loader_config/cyp/cyp_r1.py

cyp prospectus link added and opens time changed to 10am

cyp-prospectus

---

config/fund_loader_config/cyp/cyp_r1.py

https://dluhcdigital.atlassian.net/browse/FS-3500
Updating link tree to match correct form

Updating link tree

---

config/fund_loader_config/cyp/cyp_r1.py
scripts/data_updates/FS-3471-application_guidance.py

Application guidance field updated for CYP to include link to all questions page
Pull this branch
Launch the fund store
Open a bash prompt in the fund-store container and execute
`python -m scripts.data_updates.FS-3471-application_guidance`
You should see the link in the authenticator and frontend pages that show it, as per screenshots
**Frontend**
**Authenticator**

fs-3471 updating application guidance for cyp

---

config/fund_loader_config/cyp/cyp_r1.py
scripts/data_updates/FS-3471-application_guidance.py
scripts/data_updates/patch_cyp_name.py
tests/test_data_update_scripts.py

Adding 's to cyp fund title

---

scripts/data_updates/README.md

Just added notes to readme for running data scripts

bau adding notes on running data scripts

---

config/fund_loader_config/digital_planning/dpi_r2.py

Adding back F string to fix prospectus error

Fix prospect link

---

config/fund_loader_config/digital_planning/dpi_r2.py

Adding missing form for dataset information

Bau missing dataset form

---

config/fund_loader_config/digital_planning/dpi_r2.py

Adding feedback, changing date and slight text change

Changes to dpi fund

---

config/fund_loader_config/digital_planning/dpi_r2.py

Updating missing link for before you start

FS 3620 Updating before you start link

---

.github/workflows/deploy.yml
copilot/environments/addons/assessment-import-queue.yml
copilot/environments/addons/form-uploads.yml
copilot/environments/addons/funding-service-magic-links.yml
copilot/environments/dev/manifest.yml
copilot/environments/test/manifest.yml
scripts/migration-task-script.py

* Add updated environment files
* Add parametised script
* Update workflow to match
- [ X ] Unit tests and other appropriate tests added or updated
- [ X ] README and other documentation has been updated / added (if needed)

FS-3207 Copilot updates

---

config/fund_loader_config/digital_planning/dpi_r2.py

Url were the wrong way round, switching them

BAU Switching URLS

---

scripts/all_questions/metadata_utils.py

Forgot to pass in lang param to welsh yes/no was coming out in english

Fixing language bug for yes/no fields

---

README.md
config/fund_loader_config/cyp/cyp_r1.py
scripts/data_updates/patch_cypr1_guidance_201023.py

https://dluhcdigital.atlassian.net/browse/FS-3649

add url and script to ammend in place

---

api/routes.py

- Add CYP config for flag allocation teams

FS-3657: Add CYP flag allocation config

---

.github/workflows/copilot_deploy.yml

_Add ticket reference to Pull Request title: e.g. 'FS-123: Add content', if there is no ticket prefix with BAU_

BAU Concurrent and finalise workflow

---

copilot/fsd-fund-store/manifest.yml

* Adding uat and production values to copilot config
+ref: FS-3780
+semver: minor
- [N/A] Unit tests and other appropriate tests added or updated
- [N/A] README and other documentation has been updated / added (if needed)
- [*] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")

FS-3780 Updating manifest

---

.github/workflows/copilot_deploy.yml

Adding a quick check to confirm what copilot sees as an environment is what the workflow sees as the environment
+ref: FS-3780
+semver: minor
- [n/a] Unit tests and other appropriate tests added or updated

FS-3780 Confirm environment

---

.github/workflows/copilot_deploy.yml
copilot/fsd-fund-store/manifest.yml

* Add database migration scripts to the workflow
* Double task count
+ref: FS-3799
+semver: minor

Increase task count and add in migration scripts

---

config/fund_loader_config/cof/cof_r3.py

Mark as complete enabled to cof r3w3

BAU - Enable mark as complete

---

.github/workflows/deploy.yml
.github/workflows/manual-dev-deploy.yml

* Updating secrets to pass through an organization token instead of a PAT
+ref: FS-3826
+semver: minor
- [N/A] Unit tests and other appropriate tests added or updated
- [N/A] README and other documentation has been updated / added (if needed)

FS-3826 - Replacing secrets

---

config/fund_loader_config/cof/cof_r3.py

Adding the correct closing dates for COF R3W3
Also updating the correct time for Opening

BAU Updating closing dates for W3

---

.github/workflows/copilot_deploy.yml
copilot/fsd-fund-store/manifest.yml

* Seperate out release deployments from sandbox deployments
* Increase resource requirements
+ref: FS-3797
+semver: minor
- [N/A] Unit tests and other appropriate tests added or updated
- [N/A] README and other documentation has been updated / added (if needed)

FS-3797 - Rearrange copilot deploy workflow

---

.github/workflows/copilot_deploy.yml

* Paketo package.yml in workflows repo automatically tags latest when packaging on the main branch
+ref: FS-3797
+semver: minor
- [N/A] Unit tests and other appropriate tests added or updated
- [N/A] README and other documentation has been updated / added (if needed)

FS-3797 - Readding main === latest tags

---

.github/workflows/copilot_deploy.yml
copilot/fsd-fund-store/manifest.yml

Use prod as the environment name rather than prod. Leave alone the configuration used by FLASK_ENV.

change name `production` to `prod`

---

config/fund_loader_config/cof/cof_r3.py
scripts/data_updates/FS-3866_fix_incorrect_instructions_url.py

https://dluhcdigital.atlassian.net/browse/FS-3866
Fix Incorrect URL is used for express your interest hyperlink
To run the script, find the container ID for the fund-store and execute
`docker exec -it <fund_store_container_id> python -m scripts.data_updates.FS-3866_fix_incorrect_instructions_url`
To run on cloud foundry, use cf run-task
`cf run-task funding-service-design-fund-store-test --command "python -m scripts.data_updates.FS-3866_fix_incorrect_instructions_url"`

FS-3866 update round instructions for cof r3w3

---

copilot/fsd-fund-store/addons/fsd-fund-store-cluster.yml

FS-3880 - Change DB storage-at-rest to be encrypted as a result of PEN testing
- [n/a] Unit tests and other appropriate tests added or updated
NOTE: Deletes the database so data re-migration is required.

FS-3880 - Encrypt DBs

---

config/fund_loader_config/cof/cof_r3.py

Fixed conflicting translations on cof r3

Fixed translation in cof r3 config

---

db/queries.py
scripts/data_updates/FS-3859_patch_cof_r3w3_section_names.py

Added data update script for FS-3859

Added data update script for welsh translation

---

api/routes.py

-  Add flag allocation teams cof r3w2

FS-3970: Add flag allocation teams cof r3w2

---

copilot/fsd-fund-store/addons/fsd-fund-store-cluster.yml

Update the infrastructure to export the security group, so that it can be utilised in other locations
- [ N/A ] Unit tests and other appropriate tests added or updated
- [ N/A ] README and other documentation has been updated / added (if needed)

Add Fund store Security Group Export

---

copilot/fsd-fund-store/addons/fsd-fund-store-cluster.yml

https://dluhcdigital.atlassian.net/browse/FS-3945
Increase retention from 1 day to 8
- [n/a] Unit tests and other appropriate tests added or updated
Applied to dev and checked retention period has been amended.

FS-3945 Increase retention period to 8 days

---

config/fund_loader_config/cof/eoi.py
config/fund_loader_config/cof/shared.py

https://dluhcdigital.atlassian.net/browse/FS-4072
https://dluhcdigital.atlassian.net/browse/FS-4073
https://dluhcdigital.atlassian.net/browse/FS-4074
https://dluhcdigital.atlassian.net/browse/FS-4075
EOI Fixes
linked PR https://github.com/communitiesuk/funding-service-design-frontend/pull/535

Fs 4072 4073 4074 4075 eoi fixes

---

config/fund_loader_config/cof/eoi.py

https://dluhcdigital.atlassian.net/browse/FS-4083
set EOI section feedback optional

FS-4083 set eoi section feedback optional

---

config/fund_loader_config/cof/eoi.py
config/fund_loader_config/cof/eoi_r1_schema.py
tests/test_eoi_schema.py

https://dluhcdigital.atlassian.net/browse/FS-4136
https://dluhcdigital.atlassian.net/browse/FS-4076
Update the key & value - EOI schema

FS-4136 Update EOI schema

---

config/fund_loader_config/cof/eoi.py

Updating section config to rename forms

fs-4134 renaming forms

---

config/fund_loader_config/cof/eoi.py

Updated project name field to use organisation name for EOI

fs-4172 updating project name field

---

config/fund_loader_config/cof/eoi.py

Updating fund name in loader config for EOI

fs-4181 updated fund name

---

config/fund_loader_config/cof/cof_r4.py
config/fund_loader_config/cof/eoi.py

https://dluhcdigital.atlassian.net/browse/FS-4106
Correcting the contact email for EOI
Updating r4 to correct date

FS-4106 Updating fund date and contact name

---

config/fund_loader_config/cof/eoi.py

BAU Reverting contact email email back

---

config/fund_loader_config/cof/eoi.py

Updating assessment start date for EOI so that links show correctly on the landing page

Updating assessment start date

---

config/fund_loader_config/cof/eoi.py

https://dluhcdigital.atlassian.net/browse/FS-4096
Adding welsh forms to the fund

FS-4096 adding welsh forms to fund

---

api/routes.py

https://dluhcdigital.atlassian.net/browse/FS-4145
Added team allocations for COF R4W1

FS-4145 teams for cof r4w1

---

config/fund_loader_config/cof/cof_r4.py
config/fund_loader_config/cof/eoi.py

https://dluhcdigital.atlassian.net/browse/FS-4231
Updating time of EOI and COFR4

Fs 4231 - Change to date and adding missing translations

---

api/routes.py
config/fund_loader_config/cof/eoi.py
config/fund_loader_config/cof/eoi_r1_schema.py
tests/test_data/cof_eoi.json
tests/test_eoi_schema.py

- Make EOI schema a dictionary with key as langauge code
- Add Welsh translations for COF EOI schema
- Fix `Yes, a town, parish or community council` string being wrong
---

FS-4192: Add Welsh compatibility for EOI

---

config/fund_loader_config/cof/eoi.py

https://dluhcdigital.atlassian.net/browse/FS-4239
Updating cof EOI fund name to include welsh expression of interest

FS-4239 - Updating EOI welsh title

---

config/fund_loader_config/cof/eoi_r1_schema.py
tests/test_eoi_schema.py

-  Change EOI schema to match "Not sure" change
- Relevant commit: https://github.com/communitiesuk/digital-form-builder/commit/578a0e8d51bfaddc5122e157bb7624754130fb05

BAU: Change EOI schema to match "Not sure" change

---

config/fund_loader_config/cof/cof_r4.py

FS-4272 - Updating date for COF R4

---

.github/workflows/copilot_deploy.yml

Correcting trigger paths for deployments to prevent need for manual deploys

fixing trigger paths for deploys

---

scripts/amend_round_dates.py

Updated the script for amending round dates to work with the assessment start date

fs-4268 adding assessment start to amend round dates script

---

config/fund_loader_config/hsra/hsra.py

https://dluhcdigital.atlassian.net/browse/FS-4345
Fix for new application not displaying the entered application name

FS-4345 Adding project name to hsra config

---

config/fund_loader_config/cof/deprecated_fund_config/sort_application_sections.py
scripts/amend_round_dates.py

https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?selectedIssue=FS-4375
HSRA R1 configuration added to the script amend_round_date that would allow to change the dates

FS-4375-update-script-amend-round-dates-for-hsra-r1

---

scripts/amend_round_dates.py

- https://dluhcdigital.atlassian.net/browse/FS-4385
- COF R4W2 added in amend round dates script

FS-4385: COF R4W2 added in amend round dates script

---

config/fund_loader_config/cof/cof_r4.py

- https://dluhcdigital.atlassian.net/browse/FS-4387
- Code refactor to fix the issue

FS-4387: Project information form is missing from the tasklist page

---

config/fund_loader_config/cof/cof_r4.py

https://dluhcdigital.atlassian.net/browse/FS-4388
Adding an assesment start date for COFR4W2

FS-4388 Adding assesment start date for COFR4W2

---

config/fund_loader_config/hsra/hsra.py

https://dluhcdigital.atlassian.net/browse/FS-4389
- HSRA Start date added
- HSRA Round name added

FS-4389: HSRA-Start-date-and-round-name-added

---

config/fund_loader_config/cof/eoi_r1_schema.py
requirements-dev.txt
requirements.txt
tests/test_eoi_schema.py

BAU-FSD-Utils-Updated

---

config/envs/production.py
scripts/data_updates/README.md

remove PaaS specific references
(These are no longer used post PaaS migration)
App should still deploy successfully

BAU: remove PaaS specific references

---

api/routes.py
app.py
tests/test_db_routes.py

Bugfix: Add fix to handle invalid fund_id(uuid) 
- [ x] Unit tests and other appropriate tests added or updated

Bugfix: Handle exception for invalid fund_id(uuid) 

---

config/fund_loader_config/FAB/cof_25_eoi.py

Adding EOI decision schema to EOI config. This isn't in FAB. Have pasted in the actual schema not reusing the existing variable as the import script needs changing to do that

adding decision schema to COF25-eoi

---

config/fund_loader_config/FAB/cof_25.py
config/fund_loader_config/FAB/cof_25_eoi.py

Config updated after latest export from fab for COF25 and COF25-EOI

New fab export cof 25
