.github/workflows/deploy.yml, README.md
Jira Ticket:
https://digital.dclg.gov.uk/jira/browse/FS-898
I have added three environment variables called users, spawn-rate and run-time which can be used to override the locust config if they need to be set differently for fund store rather than use the default values set in deploy.yml in the workflows repo:
https://github.com/communitiesuk/funding-design-service-workflows/blob/main/.github/workflows/deploy.yml
I have also updated the README. 
NOTE: That following the recent changes done here:
https://github.com/communitiesuk/funding-design-service-workflows/pull/6
The performance tests will only run on the main branch.
=> FS-898 - Add env variables to yaml to override locust configs for fund store

dockerfile
Previously build was failing with `Exception: command 'gcc' failed: No such file or directory` due to a nested dependency. Switch to non-slim image which includes `gcc`.
=> FS-657: fix dockerfile

README.md, core/data_operations/fund_data.py, core/data_operations/round_data.py, core/dummy_dao.py, manifest.yml, openapi/components.yml, tests/test_data.py, tests/test_funds.py
The fund store will be our source of truth for the fundamental meta data that represents funds and their associated rounds.  For go live, there's no reason to have a database backing this store as the meta data is simple and we only have one fund and one round to start with.
I have however made a number of changes to the model and the resulting contract that I felt were appropriate when configuring the fund and round for COF:
- fund_id is no longer generated when the fund is created in the DAO from a slug, the id is now explicit and is a guid
- fund_id has been renamed to id
- description and name fields are no longer prefixed with "fund" - the model is about a fund, we don't need that additional information
- round_id is no longer generated when the round is created in the DAO as a slug, …
=> FS-885 and FS-886 Configuring COF fund and round and some data model changes

core/data_operations/fund_data.py
add fund `short_name` to model for use in user friendly application reference
=> FS-1406: add fund short_name to model for use in user friendly application reference

core/data_operations/fund_data.py, core/data_operations/round_data.py, core/dummy_dao.py, tests/test_funds.py, tests/test_healthcheck.py
We need to be able to easily change/add phone numbers, text phone and email address to the help sections spread throughout authenticator and frontend without having to make lots of content PRs after we go live.
Adding to Round model here to include this information, allowing us to make a single PR to change these details as required.
From a model perspective, opening hours and contact details do belong to a round.
=> Updating round model to include contact details and support availability

manifest.yml
Implements utils feature to pass through the `GITHUB_SHA` for Sentry releases.
=> FS-1677: pass through github sha

config/envs/default.py, core/data_operations/round_data.py
Add config option to extend deadline.
(Plan is to enable this on UAT only to re-open applications for user research)
=> FS-2147: add config option to change application deadline

core/fund_round_dao.py, core/funds.py, core/rounds.py, openapi/api.yml, tests/test_cof_data.py, tests/test_data.py, tests/test_funds.py
Updated the /funds/<fund_id> and /funds/<fund_id>/rounds/ endpoints to allow lookup via the short name of the fund if `use_short_name=true` is present in the querystring.
To do:
- Update the /funds/<fund_id>/rounds/<round_id> endpoint to work with short names as well for consistency??
=> adding ability to get data using short name

.github/workflows/tag-to-release.yaml
Change description
Since moving to an Enterprise org it appears GITHUB_TOKEN has defaulted to restricted permissions as described in https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token so we need to specify the correct permissions for our workflows.
[ - ] Unit tests and other appropriate tests added or updated
[ - ] README and other documentation has been updated / added (if needed)
[ - ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
How to test
If manual testing is needed, give suggested testing steps
Screenshots of UI changes (if applicable)
=> update tagging action permissions

config/fund_loader_config/night_shelter/ns_r2.py
Updating the deadline date to be 7th July 2023. Already updated direct in DBs in all envs, updating script now for audit and history purposes.
=> Updating NSTF R2 deadline date

db/migrations/versions/108033941f74_.py, db/models/fund.py
- Add `all_uploaded_documents_section_available` to funds
- Determines whether the "all_uploaded_documents" psuedo-theme is available for a fund on assessment
- Add migration script, COF has this feature, and NSTF does not
---
- https://github.com/communitiesuk/funding-service-design-assessment-store/pull/227
- https://github.com/communitiesuk/funding-service-design-assessment/pull/319
=> FS-3184: Add "All uploaded documents" functionality

config/fund_loader_config/cof/cof_r3.py
- Was previously referencing old form names
- Changed to r3w2 form names
Deleted old script inserts from database manually on test/uat:
```sql
DELETE FROM form_name 
WHERE section_id IN (SELECT id FROM section WHERE round_id = '6af19a5e-9cae-4f00-9194-cf10d2d7c8a7');
```
```sql
DELETE FROM section WHERE round_id = '6af19a5e-9cae-4f00-9194-cf10d2d7c8a7';
```
=> FS-3375: Fix COFR3W2 filename references in import script

.github/workflows/deploy.yml
At the moment, when manually run, copilot runs by default. There is currently no copilot resources to run _against_,. so with a manual run the run will go down the copilot path every time. This commit fixes that with proper verification of parameters passed
- [ N/A ] Unit tests and other appropriate tests added or updated
- [ N/A ] README and other documentation has been updated / added (if needed)
=> FS-3207: Fixing manual deployment

scripts/all_questions/metadata_utils.py, tests/test_generate_all_questions.py
FS-3704 identifies that the max words info was missing for some fields. I've added the missing field types and also included it when there isn't a hint for that question.
=> fs-3704 fixing max words by adding more field types

config/fund_loader_config/digital_planning/dpi_r2.py, scripts/data_updates/FS-3749_dpif_guidance_url.py
https://dluhcdigital.atlassian.net/browse/FS-3749
Assessment criteria link added for DPIF assessors
To run the script, find the container ID for the fund-store and execute
`docker exec -it <fund_store_container_id> python -m scripts.data_updates.FS-3749_dpif_guidance_url`
To run on cloud foundry, use `cf run-task`
`cf run-task funding-service-design-fund-store-test --command "python -m scripts.data_updates.FS-3749_dpif_guidance_url"`
=> added guidance url for dpif fund

config/fund_loader_config/cof/eoi.py
- Remove erroneous and redundant anchor tag from instructions
- The anchor was missing the initial `>` on the opening of the tag
- The anchor is hardcoded on the front-end [here](https://github.com/communitiesuk/funding-service-design-fund-store/pull/new/tferns-fs-4179-accessibility), so this was duplicated anyways
---
=> FS-4179: Remove redundant link from instructions

config/fund_loader_config/cof/eoi.py
- Tiny PR just removing the reminder date, so we don't send reminders for EOI
- This will just need the import script re-run for cof eoi
=> FS-4273: Remove reminder date for COF EOI

README.md, scripts/amend_round_dates.py
Update the amend_round_dates script to:
- Work with setting the assessment_start_date to blank
- Allow passing in of a short name for a round, not just the round id. eg. COF_R4W1
- Offer a function to reset the dates to those in the fund loader config
TODO: Update the confluence page to include example commands to eg. open a round, force open assessment etc. https://dluhcdigital.atlassian.net/wiki/spaces/FS/pages/83526002/Common+Dev+Actions#Update-local-fund-round-dates
=> Updated script to work with setting assessment_start_date to blank

copilot/fsd-fund-store/manifest.yml
-FS-4411: Overprovision instance
Change description
Reduce the number of instance to 1 in Dev and change the ECS launch_type to Fargate-spot.
Unit tests and other appropriate tests added or updated
README and other documentation has been updated / added (if needed)
Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
How to test
_Will check after deployment by logging into the ECS console and view the service and instance configuration
=> FS-4411:Over-provision instance and change to Fargate-spot

config/fund_loader_config/cof/cof_r4.py, config/fund_loader_config/cof/eoi.py
Updated the dates as follows:
**EOI**
- Application deadline: 00:01am on 25th May 2024
**COF R4W2**
- Application open, application deadline, assessment start, assessment deadline: 11:59am on 1st January *2124*
The reason for setting it far in the future is that if anyone imports this to production by mistake, it won't show up on application - if someone guesses the URL they will get the 404 as normal for rounds that don't exist or have yet to open.
=> fs-4430 updating dates for COF EOI and R4W2 following election announcement

config/fund_loader_config/hsra/hsra.py
https://dluhcdigital.atlassian.net/browse/FFE-266
- Auction-costs section removed from fund loader config for HSRA
- Run the scripts.load_all_fund_rounds and verify if auction costs is removed from the application
=> FS-4413: Auction-costs section removed from fund loader config for HSRA

config/fund_loader_config/cof/cof_r2.py, config/fund_loader_config/cof/cof_r3.py, config/fund_loader_config/cof/cof_r4.py, config/fund_loader_config/cof/eoi.py
The old COF support email was using the levellingup domain ( [cof@levellingup.gov.uk](mailto:cof@levellingup.gov.uk) ). This has been updated to the communities domain ( [cof@communities.gov.uk](mailto:cof@communities.gov.uk) )
=> Update COF support email to communities from levellingup

config/fund_loader_config/FAB/__init__.py, scripts/amend_round_dates.py
Updated the `amend_round_dates` script to work for FAB. The FAB rounds aren't hard coded in this script, so added new functions to look these up in the fab rounds folder.
- To update the dates for a round imported from fab (open application now): `python -m amend_round_dates update-round-dates-fab -f COF25 -r R1 -o PAST`
- To reset dates to the config for a round imported from fab: `python -m amend_round_dates reset-round-dates-fab -f COF25 -r R1`
Confluence updated here: https://mhclgdigital.atlassian.net/wiki/spaces/FS/pages/83526002/Common+Dev+Actions#FAB-Rounds
=> Updating amend round dates script to work for fab

config/fund_loader_config/FAB/__init__.py
Sometimes you can end up with system files in this directory (eg .DS_Store) and we don't want to read those. We only want to read fund config python files.
=> Only read python files for fund config
